---
- name: Install mongodb
  become: true
  task:
  - name: Add apt key
    apt-key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
      state: present
  - name: Add APT repository
    apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  - name: Install mogodb package
    apt:
      name: mongodb-org
      state: present
  - name: Configure service
    systemd:
      name: mongod
      enabled: yes
